name: CI

on:
  push:
    branches:
      - main
      - add-payments

permissions:
  contents: write
  packages: write

jobs:
  upload-blossom-job:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Node.js version
        run: node -v
      - name: Upload to Blossom
        uses: Origami74/upload-blossom-action@v0.0.2
        with:
          host: 'https://blossom.swissdash.site/'
          filePath: 'main.ts'