name: CI

on:
  push:
    branches:
      - main
      - add-payments

permissions:
  contents: write
  packages: write

jobs:
  upload-blossom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "hello world"
      - run: ls -la
      - run: ls ../../ -la
      - name: Get version
        run: echo "version=$(cat main.ts)"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Check Node.js version
        run: node -v
      - name: Upload to Blossom
        uses: Origami74/upload-blossom-action@debug-nektos-act
        with:
          host: 'https://blossom.swissdash.site/'
          filePath: 'main.ts'